# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [88]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [89]:
# Create a 1-dimensional NumPy array using np.array()
arr = np.array([1,2,3,4,5])
print(arr, "\n")
# Create a 2-dimensional NumPy array using np.array()
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2, "\n")
# Create a 3-dimensional Numpy array using np.array()
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]], [[11,22,33],[44,55,66],[77,88,99]]])
print(arr3)

[1 2 3 4 5] 

[[1 2 3 4]
 [5 6 7 8]] 

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]]


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [90]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)
print(arr.size)
print(type(arr))

(5,)
1
int64
5
<class 'numpy.ndarray'>


In [91]:
# Attributes of 2-dimensional array
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)
print(arr2.size)
print(type(arr2))

(2, 4)
2
int64
8
<class 'numpy.ndarray'>


In [92]:
# Attributes of 3-dimensional array
print(arr3.shape)
print(arr3.ndim)
print(arr3.dtype)
print(arr3.size)
print(type(arr3))

(2, 3, 3)
3
int64
18
<class 'numpy.ndarray'>


In [93]:
# Create an array of shape (10, 2) with only ones
array = np.ones((10, 2))
print(array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [94]:
# Create an array of shape (7, 2, 3) of only zeros
array1 = np.zeros((7,2,3))
print(array1)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [95]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [96]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
Array = np.random.randint(0, 10, (3, 5))
print(Array)

[[1 5 3 5 2]
 [5 1 1 8 6]
 [2 0 7 5 6]]


In [97]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
Array1 = np.random.rand(3, 5)
print(Array1)

[[0.00575866 0.32458583 0.36646153 0.39617269 0.69546721]
 [0.3885581  0.44869362 0.23754413 0.37325179 0.22726963]
 [0.07319592 0.60344859 0.6682128  0.61949035 0.46349404]]


In [98]:
# Set the random seed to 42
np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
Array2 = np.random.randint(0, 10, (4, 6))
print(Array2)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [100]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
A = np.random.randint(1, 10, (3, 7))
print(A, "\n")
# Find the unique numbers in the array you just created
print(np.unique(A))

[[7 8 3 1 4 2 8]
 [4 2 6 6 4 6 2]
 [2 4 8 7 9 8 5]] 

[1 2 3 4 5 6 7 8 9]


In [102]:
# Find the 0'th index of the latest array you created
print(A[0])

[7 8 3 1 4 2 8]


In [103]:
# Get the first 2 rows of latest array you created
print(A[:2])

[[7 8 3 1 4 2 8]
 [4 2 6 6 4 6 2]]


In [104]:
# Get the first 2 values of the first 2 rows of the latest array
print(A[0:2,0:2])

[[7 8]
 [4 2]]


In [105]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a=np.random.randint(0,10,(3,5))
b=np.ones((3,5))
print(a, "\n")
print(b)

[[1 4 7 9 8]
 [8 0 8 6 8]
 [7 0 7 7 2]] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [106]:
# Add the two arrays together
x_arr=np.array([1,2,3,4])
y_arr=np.array([5,6,7,8])
print(x_arr+y_arr)

[ 6  8 10 12]


In [107]:
# Create another array of ones of shape (5, 3)
arrays=np.ones((5,3))
print(arrays)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [108]:
# Try add the array of ones and the other most recent array together
print(arrays+a)

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?
By transposing one of the arrays

In [110]:
print(arrays+a.T)

[[ 2.  9.  8.]
 [ 5.  1.  1.]
 [ 8.  9.  8.]
 [10.  7.  8.]
 [ 9.  9.  3.]]


In [111]:
# Create another array of ones of shape (3, 5)
s_arr= np.ones((3,5))
print(s_arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [113]:
# Subtract the new array of ones from the other most recent array
print(a-s_arr)

[[ 0.  3.  6.  8.  7.]
 [ 7. -1.  7.  5.  7.]
 [ 6. -1.  6.  6.  1.]]


In [115]:
# Multiply the ones array with the latest array
print(a*s_arr)

[[1. 4. 7. 9. 8.]
 [8. 0. 8. 6. 8.]
 [7. 0. 7. 7. 2.]]


In [117]:
# Take the latest array to the power of 2 using '**'
d= a**2
print(d)

[[ 1 16 49 81 64]
 [64  0 64 36 64]
 [49  0 49 49  4]]


In [119]:
# Do the same thing with np.square()
sq_arr= np.square(a)
print(sq_arr)

[[ 1 16 49 81 64]
 [64  0 64 36 64]
 [49  0 49 49  4]]


In [121]:
# Find the mean of the latest array using np.mean()
m_arr=np.mean(sq_arr)
print(m_arr)

39.333333333333336


In [123]:
# Find the maximum of the latest array using np.max()
M_arr=np.max(sq_arr)
print(M_arr)

81


In [125]:
# Find the minimum of the latest array using np.min()
n_arr=np.min(sq_arr)
print(n_arr)

0


In [127]:
# Find the standard deviation of the latest array
sd_arr = np.std(sq_arr)
print(sd_arr)

26.97076606665488


In [130]:
# Find the variance of the latest array
v_arr=np.var(sq_arr)
print(v_arr)

727.4222222222223


In [134]:
# Reshape the latest array to (3, 5, 1)
reshape_arr = sq_arr.reshape(3,5,1)
print(reshape_arr)

[[[ 1]
  [16]
  [49]
  [81]
  [64]]

 [[64]
  [ 0]
  [64]
  [36]
  [64]]

 [[49]
  [ 0]
  [49]
  [49]
  [ 4]]]


In [138]:
# Transpose the latest array
trans_arr = reshape_arr.T
print(trans_arr)

[[[ 1 64 49]
  [16  0  0]
  [49 64 49]
  [81 36 49]
  [64 64  4]]]


What does the transpose do?
Transpose interchages the rows and columns

In [140]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
Arr1 = np.random.randint(0,10, (3,3))
Arr2 = np.random.randint(0,10,(3,2))
print(Arr1, "\n")
print(Arr2)

[[6 6 7]
 [4 2 7]
 [5 2 0]] 

[[2 4]
 [2 0]
 [4 9]]


In [142]:
# Perform a dot product on the two newest arrays you created
dot_arr = np.dot(Arr1, Arr2)
print(dot_arr)

[[52 87]
 [40 79]
 [14 20]]


In [144]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
Arr3 = np.random.randint(0,10,(4,3))
Arr4 = np.random.randint(0,10,(4,3))
print(Arr3, "\n")
print(Arr4)

[[6 8 6]
 [0 0 8]
 [8 3 8]
 [2 6 5]] 

[[7 8 4]
 [0 2 9]
 [7 5 7]
 [8 3 0]]


In [145]:
# Perform a dot product on the two newest arrays you created
dot_prod = np.dot(Arr3, Arr4)
print(dot_prod)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?
transpose one of the arrays

In [147]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
dot_product = np.dot(Arr3, Arr4.T)
print(dot_product)

[[130  70 124  72]
 [ 32  72  56   0]
 [112  78 127  73]
 [ 82  57  79  34]]


Notice how performing a transpose allows the dot product to happen.

Why is this? The number of columns of the first array must be equal to the number of rows of the second array

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [161]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr_x = np.random.randint(0,10,(3,3))
arr_y = np.random.randint(0,10,(3,3))
print(arr_x, "\n")
print(arr_y)

[[7 0 8]
 [8 1 6]
 [9 2 6]] 

[[9 8 3]
 [0 1 0]
 [4 4 6]]


In [163]:
# Compare the two arrays with '>'
compare = arr_x > arr_y
print(compare)

[[False False  True]
 [ True False  True]
 [ True False False]]


What happens when you compare the arrays with `>`?
It returns boolean value for the compared value according to the condition

In [165]:
# Compare the two arrays with '>='
comparision = arr_x >= arr_y
print(comparision)

[[False False  True]
 [ True  True  True]
 [ True False  True]]


In [167]:
# Find which elements of the first array are greater than 7
great_arr = arr_x > 7
print(great_arr)

[[False False  True]
 [ True False False]
 [ True False False]]


In [169]:
# Which parts of each array are equal? (try using '==')
equal_arr = arr_x == arr_y
print(equal_arr)

[[False False False]
 [False  True False]
 [False False  True]]


In [172]:
# Sort one of the arrays you just created in ascending order
sort_arr = np.sort(arr_x)
print(sort_arr)

[[0 7 8]
 [1 6 8]
 [2 6 9]]


In [175]:
# Sort the indexes of one of the arrays you just created
index_sort = np.argsort(arr_x)
print(index_sort)

[[1 0 2]
 [1 2 0]
 [1 2 0]]


In [178]:
# Find the index with the maximum value in one of the arrays you've created
max_index = np.argmax(arr_x)
print(max_index)

6


In [181]:
# Find the index with the minimum value in one of the arrays you've created
min_index = np.argmin(arr_x)
print(min_index)

1


In [183]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
max_axis1 = np.argmax(arr_x, axis=1)
print(max_axis1)

[2 0 0]


In [185]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
min_axis0 = np.argmin(arr_x, axis=0)
print(min_axis0)

[0 0 1]


In [187]:
# Create an array of normally distributed random numbers
normal_arr = np.random.randn(3,4)
print(normal_arr)

[[-1.1913035   0.65655361 -0.97468167  0.7870846 ]
 [ 1.15859558 -0.82068232  0.96337613  0.41278093]
 [ 0.82206016  1.89679298 -0.24538812 -0.75373616]]


In [189]:
# Create an array with 10 evenly spaced numbers between 1 and 100
evenly_arr = np.linspace(1, 100, 10)
print(evenly_arr)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.

What happens when you try to broadcast a (3,) array with a (4,) array?

Explain why this operation might fail and how to fix it.
To broadcast arrays, the arrays must have same dimensions and same number of elements. Here (3,) array has 3 elements where as (4,) array has 4 elements. since the dimensions are not equal, it shows error. The error can be avoided by reshaping one of the arrays to make the dimensions equal.

In [193]:
broad_arr1 = np.random.randint(0,10,(3,))
broad_arr2 = np.random.randint(0,10,(4,))
print(broad_arr1)
print(broad_arr2, "\n")
broad_arr = np.resize(broad_arr1,(4,))
print(broad_arr2+broad_arr)

[4 7 0]
[4 2 0 3] 

[8 9 0 7]


Write a NumPy program to add a 1D array of shape (3,) to a 2D array of shape (2, 3).


In [194]:
arr_1d = np.array([10,30,50])
arr_2d = np.array([[20,40,60],[90,80,70]])
sum = arr_1d + arr_2d
print(sum)

[[ 30  70 110]
 [100 110 120]]


Add a 1D array [10, 20, 30] to each row of a 2D array [[1, 2, 3], [4, 5, 6], [7, 8, 9]].

In [195]:
Arr_1D = np.array([10,20,30])
Arr_2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
add = Arr_1D + Arr_2D
print(add)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


Attempt to add a 1D array [10, 20] to a 2D array [[1, 2, 3], [4, 5, 6]]. Explain the error.

In [196]:
Array_1D = np.array([10,20])
Array_2D = np.array([[1, 2, 3], [4, 5, 6]])
addition = Array_1D + Array_2D
print(addition)

ValueError: operands could not be broadcast together with shapes (2,) (2,3) 

The shapes of the two arrays are different hence they cannot be broadcasted together. The shape of the two arrays must be equal for them to be broadcasted together.

Multiply a 2D array [[1, 2], [3, 4]] with a 1D array [10, 20] using broadcasting.

In [198]:
array_1D = np.array([10,20])
array_2D = np.array([[1,2],[3,4]])
product = array_1D * array_2D
print(product)

[[10 40]
 [30 80]]
